name: multigai
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.11.4=h06a4308_0
  - icu=75.1=he02047a_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgomp=15.1.0=h767d61c_3
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.50.3=hee844dc_1
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.1=h7b32b05_0
  - pip=25.1.1=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=py310h06a4308_0
  - tk=8.6.13=noxft_hd72426e_102
  - typing_extensions=4.15.0=py310h06a4308_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - anndata==0.11.4
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-api-compat==1.12.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.0.5
      - attrs==25.4.0
      - babel==2.17.0
      - bamnostic==1.2
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.17
      - decorator==5.2.1
      - defusedxml==0.7.1
      - episcanpy==0.4.0
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - figshare==0.1.2
      - filelock==3.13.1
      - fonttools==4.59.0
      - fqdn==1.5.1
      - fsspec==2024.6.1
      - h11==0.16.0
      - h5py==3.14.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.11
      - intervaltree==3.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-console==6.6.3
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.8
      - kneed==0.8.5
      - lark==1.3.1
      - legacy-api-wrap==1.4.1
      - llvmlite==0.44.0
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mistune==3.1.4
      - mpmath==1.3.0
      - mudata==0.3.2
      - muon==0.1.7
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook==7.5.0
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.25.2
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - patsy==1.0.1
      - pillow==11.3.0
      - platformdirs==4.5.0
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - protobuf==6.31.1
      - psutil==7.1.3
      - pycparser==2.23
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - pysam==0.23.3
      - python-json-logger==4.0.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - scanpy==1.11.3
      - scikit-learn==1.7.1
      - scikit-misc==0.5.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - session-info2==0.2
      - setuptools-scm==9.2.2
      - sortedcontainers==2.4.0
      - soupsieve==2.8
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tbb==2021.13.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.3.0
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - tornado==6.5.2
      - tqdm==4.67.1
      - triton==3.2.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
